# Generated by Django 5.0.4 on 2026-04-28 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoleccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_combustible', to='recoleccion.periodo'),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_combustible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocomprasconsumibles',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_compras', to='recoleccion.periodo'),
        ),
        migrations.AddField(
            model_name='registrocomprasconsumibles',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_energia', to='recoleccion.periodo'),
        ),
        migrations.AddField(
            model_name='registroenergia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_energia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrologistica',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_logistica', to='recoleccion.periodo'),
        ),
        migrations.AddField(
            model_name='registrologistica',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_logistica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroresiduos',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_residuos', to='recoleccion.periodo'),
        ),
        migrations.AddField(
            model_name='registroresiduos',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_residuos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('anio', 'mes')},
        ),
    ]
