# Generated by Django 5.0.4 on 2026-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('total_tco2e', models.DecimalField(decimal_places=6, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Línea Base',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tco2e', models.DecimalField(decimal_places=6, max_digits=14)),
                ('energia_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('combustible_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('logistica_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('compras_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('residuos_tco2e', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('detalle_json', models.JSONField(help_text='Detalle completo del cálculo')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado de Cálculo',
                'verbose_name_plural': 'Resultados de Cálculo',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
