# Generated by Django 5.0.4 on 2026-04-28 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.CharField(choices=[('diesel', 'Diésel'), ('gasolina', 'Gasolina'), ('gas_natural_v', 'Gas Natural Vehicular'), ('biodiesel', 'Biodiésel'), ('otro', 'Otro')], max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('camion', 'Camión'), ('furgon', 'Furgón'), ('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('otro', 'Otro')], max_length=20)),
                ('placa_o_equipo', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='soportes/combustible/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Combustible',
                'verbose_name_plural': 'Registros de Combustible',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroComprasConsumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('papel', 'Papel y materiales de oficina'), ('plasticos', 'Plásticos'), ('quimicos', 'Químicos e insumos industriales'), ('alimentos', 'Alimentos y bebidas'), ('electronico', 'Equipos electrónicos'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad', models.CharField(max_length=30)),
                ('peso_total_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('costo_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('origen_nacional', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='soportes/compras/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Compras/Consumibles',
                'verbose_name_plural': 'Registros de Compras/Consumibles',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_energia', models.CharField(choices=[('electrica', 'Eléctrica (Red)'), ('solar', 'Solar'), ('gas_natural', 'Gas Natural'), ('glp', 'GLP (Propano/Butano)'), ('otro', 'Otro')], max_length=20)),
                ('sede', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='soportes/energia/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Energía',
                'verbose_name_plural': 'Registros de Energía',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('tipo_transporte', models.CharField(max_length=50)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_toneladas', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('numero_viajes', models.PositiveIntegerField(default=1)),
                ('proveedor_logistico', models.CharField(blank=True, max_length=100)),
                ('costo_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Logística',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='RegistroResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_residuo', models.CharField(choices=[('ordinario', 'Ordinario / No reciclable'), ('reciclable', 'Reciclable'), ('organico', 'Orgánico'), ('peligroso', 'Peligroso (RESPEL)'), ('especial', 'Especial (RAEE, escombros, etc.)')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('cantidad_kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_disposicion', models.CharField(choices=[('relleno', 'Relleno sanitario'), ('reciclaje', 'Reciclaje'), ('compostaje', 'Compostaje'), ('incineracion', 'Incineración'), ('gestor_autorizado', 'Gestor autorizado RESPEL'), ('otro', 'Otro')], max_length=25)),
                ('gestor_externo', models.CharField(blank=True, max_length=150)),
                ('costo_disposicion_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('certificado_disposicion', models.FileField(blank=True, null=True, upload_to='soportes/residuos/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Residuos',
                'verbose_name_plural': 'Registros de Residuos',
                'ordering': ['-periodo__anio', '-periodo__mes'],
            },
        ),
    ]
