# Generated by Django 5.0.4 on 2026-04-28 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoleccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(help_text='energia, combustible, logistica, compras, residuos', max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('valor_actual', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_promedio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('desviacion_pct', models.DecimalField(decimal_places=2, help_text='% de desviación sobre el promedio', max_digits=8)),
                ('unidad', models.CharField(default='kWh', max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('resuelta', 'Resuelta'), ('descartada', 'Descartada (falso positivo)')], default='nueva', max_length=15)),
                ('comentario', models.TextField(blank=True, help_text='Observación del responsable al revisar')),
                ('detectada_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='recoleccion.periodo')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalía',
                'verbose_name_plural': 'Anomalías',
                'ordering': ['-desviacion_pct'],
            },
        ),
    ]
