# Generated by Django 5.0.4 on 2026-04-28 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDesviacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso en cronograma'), ('sin_evidencia', 'Sin evidencias recientes'), ('meta_riesgo', 'Meta en riesgo')], max_length=20)),
                ('mensaje', models.CharField(max_length=300)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta de Desviación',
                'verbose_name_plural': 'Alertas de Desviación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fuente_impacto', models.CharField(choices=[('energia', 'Energía'), ('combustible', 'Combustible'), ('logistica', 'Logística'), ('compras', 'Compras y consumibles'), ('residuos', 'Residuos'), ('multiple', 'Múltiples fuentes')], max_length=15)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('impacto', models.PositiveIntegerField(help_text='1=muy bajo … 5=muy alto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('costo_estimado_cop', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('factibilidad', models.PositiveIntegerField(help_text='1=muy difícil … 5=muy fácil', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reduccion_estimada_tco2e', models.DecimalField(decimal_places=4, help_text='tCO₂e que se espera reducir', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_inicio_plan', models.DateField()),
                ('fecha_fin_plan', models.DateField()),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('reduccion_real_tco2e', models.DecimalField(blank=True, decimal_places=4, help_text='tCO₂e efectivamente reducidas al completar', max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Iniciativa',
                'verbose_name_plural': 'Iniciativas',
                'ordering': ['-impacto', '-factibilidad'],
            },
        ),
        migrations.CreateModel(
            name='PlanReduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('anio_objetivo', models.PositiveIntegerField()),
                ('meta_reduccion_pct', models.DecimalField(decimal_places=2, help_text='% de reducción objetivo respecto a la línea base', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('linea_base_tco2e', models.DecimalField(decimal_places=6, help_text='Huella base desde la cual se mide la reducción', max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Reducción',
                'verbose_name_plural': 'Planes de Reducción',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
