# Generated by Django 5.0.4 on 2026-04-28 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reduccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciainiciativa',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iniciativas_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciainiciativa',
            name='iniciativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='reduccion.iniciativa'),
        ),
        migrations.AddField(
            model_name='alertadesviacion',
            name='iniciativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='reduccion.iniciativa'),
        ),
        migrations.AddField(
            model_name='planreduccion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planreduccion',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iniciativa',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to='reduccion.planreduccion'),
        ),
    ]
